### ISSUE TITLE
write covidhubutils::score_forecasts() function, as a wrapper to scoringutils::eval_forecasts() for scoring quantile and point forecasts

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covidHubUtils#10]

**Comment by nikosbosse** [comment]
This code snippet should work as expected as far as I can tell: 
```
library(magrittr)
obs <- covidHubUtils::load_truth("JHU", "Incident Death") %>%
  dplyr::rename(true_value = value) %>%
  dplyr::select(-model)
forecasts <- covidHubUtils::load_forecasts(models = c("COVIDhub-ensemble", 
                                                      "COVIDhub-baseline"),
                                           last_forecast_date = as.Date("2020-10-05"), 
                                           forecast_date_window_size = 3,
                                           source = "zoltar", 
                                           types = "quantile")
data <- dplyr::inner_join(forecasts, obs) %>%
  dplyr::rename(prediction = value)
data %>% 
  dplyr::filter(inc_cum == "inc") %>%
  scoringutils::eval_forecasts(summarise_by = c("model", "range", "quantile"))
```

**Comment by elray1** [comment]
See also Issue #5

**Comment by nikosbosse** [comment]
would you want / need any more involvement for my side, or will you take care of it?

**Comment by nickreich** [comment]
@ydhuang28 I think we will want to solve #21 before attempting this, as there is a dependency on the structure of load_forecast() queries here.

**Comment by nickreich** [comment]
Moving relevant documentation from #5 (via @elray1 )  to this issue:
```
#' Score forecasts
#'
#' @param forecast_data optional data frame with forecasts in the format returned by load_forecasts
#' @param truth_data optional data frame with forecasts in the format returned by load_truth
#' @param scores character vector of scores to calculate: any of "wis", "wis_components", "error", "abs_error",
#' "squared_error", "interval_coverage", "quantile_coverage"
#' @param return_format string: "long" returns long format with a column for "score_name"
#' and a column for "score_value"; "wide" returns wide format with a separate column for each score.
#'
#' @return data frame with columns model, forecast_date, location, inc_cum, death_case,
#' horizon, target_end_date
#' If return_format is "long", also contains columns score_name and score_value where
#' score_name is one of wis, wis_width, wis_penalty_low, wis_penalty_high,
#' interval_coverage_ where level is 0.95 for a 95% confidence interval, or
#' quantile_coverage_ where level is 0.975 for a quantile level 0.975
#' score_value has the numeric value of the score.
#' If return_format is "wide", each calculated score is in its own column.
#'
#' @export
```
This function would essentially call the scoringutils::eval_forecasts function and do some minor reorganization of the outputs.

**Comment by ydhuang28** [comment]
I'm looking to implement it in a way that if `truth_data` does not have all the truth that the function needs to score `forecast_data`, a minimally-viable subset of `forecast_data` will be scored and a warning will be printed as to which part of truth is missing. Does that sound reasonable?

**Comment by ydhuang28** [comment]
Also the function will use the most appropriate score depending on what kind of forecast `forecast_data` has, or a combination of scores if `forecast_data` has multiple kinds of forecasts; this behavior is inherited from `scoringutils::eval_forecasts()`. Does this make the `scores` parameter redundant?

**Comment by nikosbosse** [comment]
I made an update to the eval_forecasts function (currently on a branch to be merged soon) that automatically filters out all instances where either the truth data or the forecast is missing. However, it only prints a generic warning that something was missing.

**Comment by nikosbosse** [comment]
Selecting only a few metrics is currently not yet implemented in eval_forecasts (mostly because I had not yet thought about whether it is possible to avoid a million if() statements to check whether the metric to be computed is actually desired by the user. But that should be rather easy to do, if that is a priority for you

**Comment by ydhuang28** [comment]
I was thinking about that too. Right now I'm leaning towards a design like this:

![image](https://user-images.githubusercontent.com/3778509/101206900-d044b200-363d-11eb-9d90-e86bd24471f3.jpeg)

Basically I'll remove the scores that the user didn't request and add in `NA`'s for the scores that the user did request but could not be calculated given invalid combinations of (forecast data + truth data + type of forecasts).

**Comment by nikosbosse** [comment]
Also good. For that specific use case it probably doesn't matter much whether that is implemented in eval_forecasts or in the wrapper around it. But I think at some point I would like to implement that in eval_forecasts as well, so depending on your preferences we could also just do that now (also happy to have a chat anytime if you like)

**Comment by ydhuang28** [comment]
I think @nickreich has a vision of having less duplication of efforts, so maybe we can work together on that? It sounds like you're looking for something similar, so perhaps including it directly in `eval_forecasts()` is better?

**Comment by nickreich** [comment]
Not clear to me what my input is needed for here, but I guess I support in general trying to work together so code is just written in one place without duplication.
