### ISSUE TITLE
Forecasts take a long time to load from zoltar

### ISSUE THREAD

**Issue by nikosbosse** [reichlab/covidHubUtils#12]
Retrieving forecasts with the following code took about an hour. The problem persisted in a new R session and I do not know what causes it
```
forecasts <- covidHubUtils::load_forecasts(models = c("COVIDhub-ensemble", 
                                                      "COVIDhub-baseline"),
                                           last_forecast_date = as.Date("2020-10-05"), 
                                           forecast_date_window_size = 3,
                                           source = "zoltar", 
                                           types = "quantile")
```

**Comment by nickreich** [comment]
maybe due to multiple queries issued in parallel? So we should investigate whether
 - we can reduce the splitting up of queries AND/OR
 - whether running multiple small queries in parallel is possible/desirable.

**Comment by nickreich** [comment]
I think there is something in the data processing that is making this take a while, perhaps having to do with calls to MMWRweek? I see this when I killed a query that had downloaded all the data but was taking a long time to do the post-processing
```
Called from: purrr::pmap_chr(MMWRweek::MMWRweek(lubridate::ymd(forecast_date) + 
    week_offset * 7), function(MMWRyear, MMWRweek, MMWRday) {
    as.character(MMWRweek::MMWRweek2Date(MMWRyear, MMWRweek, 
        7))
})
```

**Comment by nickreich** [comment]
this is related to https://github.com/reichlab/covidHubUtils/issues/19

**Comment by nickreich** [comment]
So the following query, when used in conjunction with the updated load_forecasts_zoltar() is relatively speedy. 
```
library(covidHubUtils)

forecasts1 <- covidHubUtils::load_forecasts(
    models = c("COVIDhub-ensemble", "COVIDhub-baseline", "YYG-ParamSearch", "UMass-MechBayes"),
    targets = paste(1:4, "wk ahead inc death"),
    last_forecast_date = as.Date("2020-10-05"),
    forecast_date_window_size = 3,
    source = "zoltar",
    types = "quantile")
```

Note, also that reducing to include a `targets` option may reduce the size of forecasts that produce county-level forecasts as well.
