### ISSUE TITLE
add message to load_forecasts() about long query times

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#13]
When zoltar is specified as the source for loading forecasts, pass a message to the R session that says something like:
"Large queries that span many combinations of forecast dates, models, locations, and targets can take a long time to process. To reduce run-time of queries, we encourage users to download a local copy of the COVID-19 Forecast Hub repository so queries can be run locally: https://github.com/reichlab/covid19-forecast-hub/."

**Comment by Serena-Wang** [comment]
done
