### ISSUE TITLE
Typo on sample code in website preview

### ISSUE THREAD

**Issue by micokoch** [reichlab/covidHubUtils#159]
Hello, I found a small typo in the sample code for running covidHubUtils (in the website preview). I've attached an image that shows where the mistake is. Under "Plot multiple models and locatios" in the plot forecast() function, it should say "facet = location~model" (not "location_name"). Hope that helps!

<img width="1131" alt="Captura de Pantalla 2021-02-17 a la(s) 10 43 54 a  m  (1)" src="https://user-images.githubusercontent.com/56451982/108235704-175a2380-7114-11eb-96fc-44eae5373cb4.png">

**Comment by ApurvShah007** [comment]
This has been solved and will be pushed in a coming PR

**Comment by nickreich** [comment]
closed by #189
