### ISSUE TITLE
allow user to provide truth data for plot_forecasts

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#16]
To match the proposal for `score_forecasts` in issue #5, the first two arguments for plot_forecasts could be

#' @param forecast_data optional data frame with forecasts in the format returned by load_forecasts
#' @param truth_data optional data frame with forecasts in the format returned by load_truth

We would only load truth data inside of `plot_forecasts` if the user didn't provide it

**Comment by Serena-Wang** [comment]
This functionality is added. You can also use 'truth_as_of' in plot_forecasts() to specify truth version in plot caption.
