### ISSUE TITLE
Error in score_forecasts

### ISSUE THREAD

**Issue by chulmelowe** [reichlab/covidHubUtils#162]
I'm getting an error message when I run the score_forecasts function saying 

`Error in (function (true_values, lower, upper, interval_range = NULL,  : 
  unused argument (count_median_twice = FALSE)`

which appears to be a reference to the `eval_forecasts` function from the `scoringutils` package. I'm thinking that maybe the `count_median_twice` argument has been depreciated since I'm using the most up to date version.

**Comment by starkari** [comment]
@chulmelowe would you be willing to share what exactly you are running as I am unable to generate this error on my end

**Comment by nikosbosse** [comment]
Are you using the github version of scoringutils (`devtools::install_github("epiforecasts/scoringutils"`)?

**Comment by chulmelowe** [comment]
Sorry it's taken me a few days to get back to this. Yes, I am using the most recent version of `scoringutils`, I've double checked that. Here is the code I ran that produced the original error message:
`library(tidyverse)
# devtools::install_github("https://github.com/reichlab/covidHubUtils")
require(covidHubUtils)
#devtools::install_github("https://github.com/epiforecasts/scoringutils")

truth_data <- load_truth(truth_source = "JHU", target_variable = "inc case", locations = "US")
case_targ  <- paste(1:4, "wk ahead inc case")
death_targ <- paste(1:4, "wk ahead inc death")
forecasts  <- load_forecasts(
  forecast_dates = seq.Date(as.Date("2020-09-06"), as.Date("2021-02-20"), by = "7 days"),
  locations = "US",
  types = c("point", "quantile"),
  targets = c(case_targ, death_targ)
)
f_scores <- score_forecasts(forecasts = forecasts, truth = truth_data, return_format = "long")
`
However, I'm no longer getting the error message. I haven't changed anything since I submitted the issue, so I'm not sure how or why I'm not getting the error.

**Comment by elray1** [comment]
I'm going to close this issue for now, but please feel free to re-open if you encounter this problem again.
