### ISSUE TITLE
utility function to load truth from covidData

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#164]
`covidData::load_data` returns data with columns `location`, `date`, `inc`, and `cum`.  It would be helpful to have:

 - a utility function that takes this output and converts it to the set of columns required for the `covidHubUtils` functions.
 - an option to `covidHubUtils::load_truth` or a separate function that loads versioned truth data from covidData.

Ideally we would not require the user to have covidData installed to install covidHubUtils (if they don't want to use the functionality described here)

**Comment by Serena-Wang** [comment]
- add `as_of` parameter
