### ISSUE TITLE
Package clean up

### ISSUE THREAD

**Issue by nikosbosse** [reichlab/covidHubUtils#171]
Related to https://github.com/reichlab/covidHubUtils/pull/170

When building the package locally I came across a lot of errors, warnings and notes. I think it would be a good idea to spend some time to clean these up. 

One error appeared with regards to covidData. `covidData::load_jhu_data` calls something called `covidData::jhu_deaths_data` which doesn't exist. I installed covidData using `devtools::install_github("reichlab/covidData")` - not sure if something else is expected. If you like I can open another issue there.

**Comment by elray1** [comment]
The covidData installation process is a bit involved; installation via `install_github` won't work.  There is documentation for how to do this in the readme file over there: https://github.com/reichlab/covidData

That said, I think we should try to keep dependencies on covidData out of covidHubUtils.  Was installation of covidData required to install covidHubUtils?

Did you have some specific other warnings or errors you encountered?

**Comment by nickreich** [comment]
Closing this issue, but please re-open with more specifics if needed.
