### ISSUE TITLE
add function for computing approximate cramer's distance between two predictive distributions

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#175]
So far, @jbracher and @NutchaW have worked on this a bit. Not sure who should take this on to develop unit tests, etc...

**Comment by aaronger** [comment]
Keep forgetting to follow up with folks about this - is there any code already written/outlined?

**Comment by NutchaW** [comment]
Not yet. I'm working on the math to improve the approximation (by allowing
unequally-spaced intervals).
I have been a bit inundated with other tasks these past couple of weeks,
but I will get to this soon.

**Comment by elray1** [comment]
I'm closing this issue since the base function is done and separate issues have been filed for refinements to this function and to aggregate the results across multiple forecasts/models
