### ISSUE TITLE
As convenient Zoltar access as possible

### ISSUE THREAD

**Issue by ryantibs** [reichlab/covidHubUtils#20]
Hi all!  I have to admit I haven't looked at the details of this package (embarrassingly, I forgot about it until @nickreich mentioned it to me just a few minutes ago).  From my recent convo with Nick: 

> we are putting together some very basic functionality for viz/scoring on covidHubUtils.  as we do this, we are creating two options for functions: either forecasts can be accessed via a "local repo" (i.e. a local clone of the repository) or via "zoltar" (in which case the user needs a Zoltar account to access the API).

We (Delphi) would love to hookup to Zoltar to pull forecast data in.  If the covidHubUtils package already has the functionality we need, then it would save us from re-implementing this in our evalcast package (see https://github.com/cmu-delphi/covidcast/issues/99).  We could just import the relevant function(s) from covidHubUtils in our package.

One thing I'm not fond of though, is the fact that the *R user* needs to sign up for a Zoltar account in order to fetch forecast data through covidHubUtils.  This would require us (in evalcast) to tell users to get a Zoltar account in order to access some of our own functionality that relates to the Covid Hub as well.  

I recognize why this (requiring an account) is in place and what benefit it provides, but can you think about having just a single "covidHubUtils" Zoltar account, so that covidHubUtils can internally fetch data from Zoltar?  Then the R user wouldn't need to do anything (except install the covidHubUtils package of course).  And we could directly benefit from this on the evalcast side.

**Comment by nickreich** [comment]
We are going to add a way for anyone to query zoltar. keep tabs on this issue, we will close this when implemented.

**Comment by ryantibs** [comment]
Awesome thank you Nick, this is great to have implemented.  We'll try it out soon.
