### ISSUE TITLE
add functionality to assist with aligning forecasts made on different forecast dates

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#247]
We often want to match up forecasts that are submitted on different forecast dates, e.g. for the purpose of scoring them or building an ensemble.  We need to keep track of three quantities to match corresponding forecasts:

1. a location forecasted, e.g. a state or county
2. a target end date
3. something to identify forecasts that were made during the same week

The main challenge here is identifying a representation for item 3 that is most useful for different analysis purposes and both day-ahead and week-ahead targets. For context, consider a running example for scoring forecasts with forecast dates between Tuesday, June 1 and Monday, June 7. For all of these forecasts, the target end date for a 1 week ahead forecast will be Saturday, June 12. The target end dates for 1 day ahead forecasts will be different since they will be one day after the forecast's corresponding `forecast_date`.

We have thought of 3 options for how the grouping variable could be defined:

1. a reference date defining the week of submission (maybe named `forecast_week_end_date`). In our running example, this might be defined to be Monday, June 7.
2. a reference date defining the date relative to which targets are defined for the purpose of the analysis at hand (maybe named `target_reference_date`): a date relative to which day-ahead or week-ahead targets should be defined for the purpose of whatever analysis is being conducted (e.g., scoring forecasts). In our running example, this might be Saturday, June 5 for weekly targets (since the 1 week ahead targets for forecasts submitted between June 1 and June 7 refer to June 12, which is 1 week after June 5) or Monday, June 7 for daily targets (since the forecast submission due date we're considering was June 7, and I could want to investigate forecast skill for a target end date of June 8, one day after that due date; for the purpose of that analysis, a 1 day ahead target is defined relative to June 7).
3. an implied "`relative_horizon`" for the purpose of the current analysis, with the horizon defined relative to the `target_reference_date` in item 2 above rather than the forecast's original `forecast_date`. In our example, all forecasts of weekly targets with a `target_end_date` of June 12 would have a `relative_horizon` of 1, and all forecasts of daily targets with a `target_end_date` of June 8 would have a `relative_horizon` of 1.

After settling on one or more representations that are most useful for everyone's purposes, we might like to include these as either (or both):

- columns returned in the default output from `covidHubUtils::load_forecasts`; and/or
- a set of utility functions to calculate these quantities based on existing columns in the output from `covidHubUtils::load_forecasts`

If we can agree on one of these that seems generally useful, my preference would be to include it as a column in the default output from `load_forecasts`, possibly with utility functions to calculate the others.

**Comment by elray1** [comment]
There are some functions for calculating quantities along these lines here (though with inconsistent naming conventions, different from what's in the proposal above): https://github.com/reichlab/covidEnsembles/blob/master/R/date_management.R

**Comment by nickreich** [comment]
Here's a slightly modified/clarified version of the above options:

 - define a `forecast_week_end_date` column that would have a Saturday date in it (in the example above, Saturday June 5) representing the "end date of the week that the submission corresponds to". This is a little weird because forecasts submitted on Sunday June 6 and Monday June 7 would also have forecast week end date of June 5, but we could live with it and this is a natural extension of our existing "target_end_date" computations.
 - define a `standardized_horizon` column that (a) for weekly targets would be the same as the already defined `horizon` (or we could define it as NA?), and (b) for daily targets would provide the daily horizon relative to the `forecast_week_end_date` defined above. E.g. a forecast submitted on June 3 would have some rows with the following values
forecast_date | target_end_date | horizon | forecast_week_end_date | standardized_horizon
--------------|-----------------|---------|-------------------------|-------------------
2021-06-01   |  2021-06-02      | 1             | 2021-06-05                     | -3
2021-06-01   |  2021-06-06      | 5             | 2021-06-05                     | 1

**Comment by nickreich** [comment]
Note that functionality for `forecast_week_end_date` already exists, e.g.
```
  mutate(forecast_week_end_date = as.Date(calc_forecast_week_end_date(forecast_date)))
```

**Comment by elray1** [comment]
For the purpose of ensemble construction, we would rather compute a "`standardized_horizon`" relative to a Monday rather than a Saturday, because ensemble forecasts of daily targets are done relative to the ensemble's forecast date, which is a Monday. If we want this to be able to support ensemble construction, this would motivate a different choice of the "reference date" used for calculating standardized horizons for daily and weekly targets.

**Comment by aaronger** [comment]
Here's possibly an alternative solution to the problem that leaves the loading functions alone:
[https://github.com/aaronger/covidHubUtils/blob/standardize/R/standardize.R](https://github.com/aaronger/covidHubUtils/blob/standardize/R/standardize.R)

I feel like I'm glossing over some complexities of the situation. But this does seem, though, like an easy way to maintain flexibility about the realignment process.

**Comment by sbfnk** [comment]
I know this probably affects quite a few functions here but it would be good if whatever solution is agreed on would be agnostic to whichever day of the week ends weeks (MMWR or other) - e.g. convention in Europe is often to define weeks Mon-Sun and using MMWR weeks has already caused us a few headaches, and we're considering changing this in the future.

Ideally this would be the kind of thing that could be stored in a [repo-specific configuration file](https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/511).

**Comment by elray1** [comment]
I like the spirit of Aaron's proposal here: it doesn't clutter up the forecasts if you don't need it, and it allows for the flexibility that's needed for different targets and hubs.

I do have some general questions though (bearing in mind I did not carefully work through the code), which might be better addressed via comments on a pull request:

- I wonder if we could base some part of this calculation on the existing function `calc_submission_due_date`, which already supports a "reference day of week" type of argument, or a version of `calc_forecast_week_end_date` that's been modified to have that argument.
- I didn't read through the code carefully, but wasn't clear about what `reference_dates` and `reference_windows` were doing.

**Comment by aaronger** [comment]
The idea with `reference_dates` and `reference_windows` is to maintain flexibility if we ever have irregular reporting patterns to accommodate (like a shift in when we report ensembles or how late we want to accept submissions).  With this approach we can worry only about getting the pattern sequence right (which is then passed directly to `reference_dates` and `reference_windows`) and not how it is or needs to be embedded into other code. 

We could of course embed the `calc...` functions into `standardize_forecasts` as default `reference_dates` providers but to be honest I'm not crazy about `lubridate::ceiling/floor` which have felt pretty brittle to me in certain testing scenarios. And while this seems like a far fetched possibility, it did occur to me that that the calc functions would be unable to help with reference windows that were interspersed.

And I'll think more about how to handle multiple responses/time-scales... seems doable - just didn't get that far.

I'll also submit the PR for line comments.

**Comment by aaronger** [comment]
OK here's the [PR](https://github.com/reichlab/covidHubUtils/pull/250).
