### ISSUE TITLE
Subset forecasts to those that are shared in common within specified groups

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#267]
If you're calculating average scores to compare across models, you want to do that for scores for location/date/horizon combinations that are shared in common for each model.  Details to be worked out, but I think it'd be helpful to have a function to subset to those common forecasts, along the lines of the following:

```
#' Subset forecasts to those that were made in common by all models.
#' 
#' @param forecasts a data frame of scores as returned by load_forecasts
#' @param grouping_variables character vector of variables specifying groups of forecasts within
#' which the user might want to compute score summaries later on.  The function will return a common
#' set of forecasts within each group defined by the grouping_variables.
#' @param id_variables character vector of variables identifying unique forecasts
#'
#' @return a data frame of scores, subset to common scores within each group.
subset_scores_to_common <- function (scores, grouping_variables, id_variables)
```

Example:

- suppose a forecast is identified by the location, forecast date, horizon, and target_var columns. Then id_variables = a character vector of those things.
- If we have a data frame of scores for locations that are counties and states, and I want to calculate interval coverage separately at the county level and state level, only for the forecasts defined by a forecast id combination that are available from all models in the scores data frame, but considered separately for the county and state level. Then the `geo_type` (county or state) would be a relevant `grouping_variable`.
- within each group defined by combination of `grouping_variable` values, look at every combination of values in the `id_variables` columns. For one combination of `id_variables` values, drop all forecasts if any model in the forecasts data frame did not have a forecast for that combination.

I have a start at code like this here that needs to be generalized:

```
subset_scores_to_common_one_group <- function(scores) {
  id_counts_by_model <- scores %>%
    dplyr::mutate(
      combined_id = paste0(location, forecast_date, target_end_date)
    ) %>%
    dplyr::count(model, combined_id) %>%
    tidyr::pivot_wider(names_from = "model", values_from = "n")
  combined_ids_to_drop <- id_counts_by_model[["combined_id"]][
    id_counts_by_model %>%
      dplyr::select(-combined_id) %>%
      as.matrix() %>%
      apply(1, function(x) { any(is.na(x)) })
  ]
  scores <- scores %>%
    dplyr::filter(
      !(paste0(location, forecast_date, target_end_date) %in% combined_ids_to_drop)
    )
  return(scores)
}

purrr::pmap_dfr(
  scores_case %>% dplyr::distinct(location_type, forecast_date, horizon),
  function(location_type, forecast_date, horizon) {
    reduced_scores <- scores %>%
      dplyr::filter(
        location_type == UQ(location_type),
        forecast_date == UQ(forecast_date),
        horizon == UQ(horizon)
      )
    subset_scores_to_common_one_group(reduced_scores)
  }
)
```

**Comment by nickreich** [comment]
This feels like a highly specialized use-case. And one that is related to but dealt with in different ways than the pairwise comparison. Would it be confusing to have different functions to handle these situations in different ways? 
I'm not averse to including this in covidHubUtils, but also don't see it as mission-critical functionality.

**Comment by elray1** [comment]
If no one would use it, let's not bother formalizing it. I think the pairwise comparison approach has its place, but also has limitations:

- to me, it's harder to interpret -- values depend on what models are in the set of models being compared, what the baseline is, how you handle inclusion of the baseline in the different steps, etc.
- i don't think it handles things like coverage rates well

**Comment by elray1** [comment]
going to close this as functionality we don't plan to use, but we can always re open it
