### ISSUE TITLE
In score_forecasts more specific error message for if missing forecasts

### ISSUE THREAD

**Issue by starkari** [reichlab/covidHubUtils#273]
Lines 88-94 in code now
See Serena's and Nick's comments in #75

**Comment by elray1** [comment]
We think that that is related to the comment "I think it would be helpful to have this error message be more specific, to have one error thrown if there was a "Required column missing" and another if "Unknown column included." (Although is the latter really a problem?)"

 - verify that this is still an issue
 - if so, take care of it

**Comment by elray1** [comment]
closing as low priority
