### ISSUE TITLE
Documentation for return value in `load_truth()` is outdated

### ISSUE THREAD

**Issue by Bisaloo** [reichlab/covidHubUtils#274]
I was looking for information about the `week_start` column we get when running:

```r
load_truth(
     target_variable = c("inc case", "inc death", "inc hosp"),
     hub = "ECDC",
)
```

But it looks like the documentation is outdated. It currently reads:

> data frame with columns model, inc_cum, death_case, target_end_date, location, value, location_name, population, geo_type, geo_value, abbreviation

It looks like `inc_cum` and `death_case` have been merged into `target_variable` but new columns have been added as well.

I'm not sure how to update it in a clear manner since the returned columns change depending on the argument values.

* The common columns seem to be:

  - `model`
  - `target_variable`
  - `target_end_date`
  - `location`
  - `value`
  - `location_name`
  - `population`

- If `truth_source = "ECDC"`, you get an extra `week_start` column
- If `hub = "US"`, you get extra columns: `geo_type`, `geo_value`, `abbreviation`, `full_location_name`

**Comment by sbfnk** [comment]
I think for "ECDC" (and maybe the others?) it depends on whether weekly or daily data is returned. I think default for ECDC is currently to return a mixture of weekly and daily data so it'll have a `week_start` column which is `NA` for the daily hospitalisations.

**Comment by Serena-Wang** [comment]
Documentation is updated now :)
