### ISSUE TITLE
change `load_forecasts()` to replace Zoltar API calls with queries against the local sqlite file when `source == "local_zoltar"`

### ISSUE THREAD

**Issue by matthewcornell** [reichlab/covidHubUtils#310]
From slack conversation b/w me, @nickreich , @elray1 , and @Serena-Wang :
> `load_forecasts()` is hitting the server multiple times for each call to it. @Serena Wang and I talked a little about this, but haven't made a decision yet. my current thinking is that, for the case `source = "local_zoltar"`, `load_forecasts()` should not hit the server at all. doing so adds time to what should be a fast and completely local call. IIUC those server calls are for validation, so maybe we could add a "is_validate=True" flag that users should set to False when `source = "local_zoltar"`.

IIUC, these are the only functions we'd need to port to run against the local sqlite3 database file:
- **zoltr::projects**(zoltar_connection)
    - API URL: /api/projects/
    - fields needed: $id, $name
- **zoltr::models**(zoltar_connection, project_url)
    - API URL:  project_url + 'models/'
    - fields needed: $id, $model_abbr
- x **zoltr::timezeros**()  _# not needed_
- **zoltr::forecasts**(zoltar_connection, model_url)
    - API URL:  model_url + 'forecasts/'
    - fields needed: $timezero_date (Note that we'd probably use IDs to identify objects, not URLs.)

**Comment by Serena-Wang** [comment]
This feature is added to load_forecasts_local_zoltar() in issue_310 branch.
