### ISSUE TITLE
create facet-ready plot_forecasts() function

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#40]
specs via google doc design.

#' @param forecast_data data frame with truth and forecasts from load_forecasts()
#' @param truth_data optional data frame with forecasts in the format returned 
#' by load_truth().
#' @param models model_abbr specifying model to plot. Optional if there is only
#' one model available in forecast data.
#' @param target_variable string specifying target type. It should be one of 
#' "cum death", "inc case", "inc death"
#' @param locations string for fips code or 'US'. Optional if there is only one
#' location available in forecast data.
#' @param facet interpretable facet option for ggplot
#’ @param facet_scales argument for scales in ggplot2::facet_wrap
#’ @param forecast_dates forecast dates to plot, defaults to forecast_dates present
#’ in the data
#' @param intervals values indicating which central prediction interval levels 
#' to plot, defaults to c(.5, .8, .95). NULL means only plotting point forecasts.
#' If not provided, it will default to all available intervals in forecast data.
#' @param horizon forecasts are plotted for the horizon time steps after the 
#' forecast date. Default to all available horizons in forecast data. 
#' @param truth_source character specifying where the truth data will
#' be loaded from if truth_data is not provided. 
#' Otherwise, this character specifies the data source to plot. 
#' Currently support "JHU","USAFacts" and "NYTimes".
#' @param truth_as_of the plot includes the truth data that would have been 
#' in real time as of the truth_as_of date (not using this parameter when truth data 
#' is from github repo)
#' @param title optional text for the title of the plot. if left as "default",
#' the title will be automatically generated. if "none", no title will be plotted. 
#' @param show.caption logical, if TRUE, caption will be included showing data sources
#’ @param plot logical; if TRUE, the plot is printed
#' 
#' @return invisible ggplot object
#' 
#' @export
plot_forecasts <- function(forecast_data,
                          truth_data = NULL, 
                          models,
                          target_variable,
                          locations,
                          forecast_dates,
                          facet,
                          intervals = c(.5, .8, .95),
                          horizon,
                          truth_source = "JHU",
                          truth_as_of = NULL, 
                          title = "default", 
                          show.caption = TRUE,
                          plot = TRUE)

**Comment by nickreich** [comment]
@elray1 asks:
"How are fill colors for geom_ribbon going to be determined?  is it just blues for all forecasts?  or maybe a color family (purples, blues, greens, reds, browns, etc) for each combination of model and forecast date in tidyr::expand_grid(models, forecast_dates)? or user option?"

**Comment by elray1** [comment]
Here's a proposal for how to handle colors:

 - `RColorBrewer::brewer.pal` is currently used to generate color scales for the intervals using `"Blues"` for the palette. There are also distinct options for Greens, Oranges, Purples, and Reds, giving us 5 fairly distinct color families.
 - If we want to plot forecasts from up to 5 models with multiple interval levels from each model, generate colors from these families (maybe in the order "Blues", "Oranges", "Purples", "Reds", "Greens" which I think is the most colorblind-friendly order?) to use in `scale_color_manual` as is done now.
 - If we want to plot forecasts from more than 5 models, show only a single interval level for each model (e.g. 95%), generate colors from some other scale with more color options

For now, we don't support colors by forecast date

**Comment by nickreich** [comment]
seems reasonable to me.
