### ISSUE TITLE
Loading weekly COVID-19 inc hosp data from Zoltar

### ISSUE THREAD

**Issue by nikosbosse** [reichlab/covidHubUtils#402]
**Update**: just realised the weekly forecasts were only available for Flu, not COVID-19. Is there an established way to automatically convert from daily to weekly forecasts, without having to deal manually with the forecast dates and target end dates? Past experience teils me that I'm not to be trusted doing these kinds of things by hand...

Second update: Given that it might not be that easy to sum up quantiles anyway, maybe there just isn't a good way to do this. 

---
I was trying to load weekly COVID-19 inc hospitalisation data, trying the following: 

```
load_forecasts(
  models = "COVIDhub-ensemble",
  # dates = "2021-07-30",
  date_window_size = 11,
  locations = "US",
  types = "quantile",
  targets = paste(1:4, "wk ahead inc hosp"),
  source = "zoltar",
  hub = "US",
  as_of = NULL
)
```

This did not work. Updating the call to `targets = paste(1:28, "day ahead inc hosp"),` did work, however, I'm not entirely sure how to get weekly forecasts from there. 
~Given that forecasts are available on GitHub (e.g. [here](https://github.com/cdcepi/FluSight-forecast-hub/blob/main/model-output/FluSight-ensemble/2024-01-13-FluSight-ensemble.csv)), I was expecting they would be available through covidHubUtils/Zoltar as well.~
Is there a  direct way to get weekly forecasts through covidHubUtils?

**Comment by nikosbosse** [comment]
Pinging @nickreich for awareness

**Comment by nickreich** [comment]
Thanks for the issue, @nikosbosse . I do think that your second update is basically correct. There is not a statistically correct way to aggregate quantile forecasts at the daily level into weekly level. Therefore, I'm going to close this issue for now. But if I'm missing something else that needs solving here, please feel free to reopen.

**Comment by nikosbosse** [comment]
Makes sense, thank you!
