### ISSUE TITLE
clean up R CMD CHECK workflow 

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#405]
- [x] [remove extraneous package installs](https://github.com/reichlab/covidHubUtils/blob/088d1b3925d3031dc4f691de21101274f44599e4/.github/workflows/r_cmd_check.yaml#L23) that confuses new users who don't have all packages installed (e.g. DT)
- [x] actually check the vignettes if possible

**Comment by bsweger** [comment]
@nickreich there's a render vignette step in the test action: https://github.com/reichlab/covidHubUtils/blob/master/.github/workflows/pr_unittest.yaml#L86

It uses the `rmarkdown::render("vignettes/covidHubUtils-overview.Rmd")` incantation, which looks like it executes the .Rmd code.

This may explain the `--no-vignettes` we see in the R CMD CHECK workflow.

Will this suffice for the second checkbox in the short term?

In the longer term, I'm going to create an issue to bring this repo's R CMD CHECK workflow in line with the corresponding workflows over in the hubverse, which make use of tools like `r-lib/actions/check-r-package@v2` ([for example](https://github.com/Infectious-Disease-Modeling-Hubs/hubValidations/blob/main/.github/workflows/R-CMD-check.yaml))

**Comment by nickreich** [comment]
I created the other issue just so we didn't lose it, and yes, I think for the short-term this should work. Let's get back to the assigned bug!

**Comment by bsweger** [comment]
Closing, as this was resolved in https://github.com/reichlab/covidHubUtils/pull/409 (I used the wrong wording to auto link the ticket)
