### ISSUE TITLE
test failures when running check() on a local copy of the package

### ISSUE THREAD

**Issue by bsweger** [reichlab/covidHubUtils#408]
As part of onboarding to this code base, I encountered a test failure when running the test suite:

- [preprocess_truth_for_zoltar works: get exactly all combinations of locations](https://github.com/reichlab/covidHubUtils/blob/088d1b3925d3031dc4f691de21101274f44599e4/tests/testthat/test-get_truth.R#L418)

We're not seeing similar failures when the tests run as part of CI because the GitHub actions task only runs these when the related code has been updated (e.g., if there's been a change in  `get_truth.R`).

Digging into the first failure, it seems that starting in October 2022, the truth data being loaded via `covidData` has fewer observations per date than we're expecting (this is after a [fix to filter out zerotruth dates from Zoltar that aren't in covidData](https://github.com/reichlab/covidHubUtils/commit/23dfb445da88072e10c4e827efa2c048a819d929))

I'd like to dig into what we're testing here and either:

* fix the test (and make sure it always runs in CI)
* remove it

**Comment by bsweger** [comment]
@nickreich @elray1 The question for you all is whether or not we need to worry that the [truth data as it exists in covidData](https://github.com/reichlab/covidData/blob/master/data/jhu_us_deaths_data_links.csv) doesn't match what this test is expecting.

I'm unsure of whether or not this test failure means that something is actually broken or if it simply reflects that the truth data hasn't been updated for a while.

**Comment by nickreich** [comment]
This was partially addressed in an internal slack thread. My feeling is that it's ok to remove the test given that we are no longer pushing truth data to zoltar, since we only were storing death and case truth data and those forecasts have been discontinued.
