### ISSUE TITLE
Write R script that uses covidData to generate csv truth data

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covidHubUtils#43]
data-truth/truth-Incident Cases.csv, data-truth/truth-Incident Cases.csv, data-truth/truth-Cumulative Cases.csv, data-truth/truth-Incident Deaths.csv, data-truth/truth-Cumulative Deaths.csv

**Comment by elray1** [comment]
I think this issue was mostly resolved by 779ce24, but do we still need to write a script that calls the functions created there and outputs the results to the appropriate folder in the covid19-forecast-hub repo?

**Comment by Khoale1096** [comment]
Should that be a script put in the covid-forecast-hub, since what it needs to do is installing covidHubUtils, then using the `preprocess_jhu()` just added to create the standard csv files? I'm not sure if a script like this should be a part of covidHubUtils.

**Comment by elray1** [comment]
Yeah that makes sense.  I'll close this issue.
