### ISSUE TITLE
unit tests for functions that create standard csv outputs truth-Cumulative Cases.csv, truth-Cumulative Deaths.csv, truth-Incident Cases.csv, truth-Incident Deaths.csv

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#46]
- [ ] Exactly the expected combinations of location, week, and target show up in the results. i.e., all expected locations in combination with every possible week so far and target, and no unexpected locations, weeks, or targets
- [ ] It's possible to correctly reconstruct cumulative values in the JHU csv file from cumulative values in the truth source. i.e., can convert from cumulative numbers in the truth file back to the jhu csv values.
- [ ] It's possible to correctly reconstruct cumulative values in the JHU csv file from incident values in the truth source. i.e., can convert from incident numbers in the truth file back to the jhu csv values.

@Khoale1096 @ydhuang28 please feel free to suggest/edit/eliminate items on this list as you think is appropriate.

**Comment by Khoale1096** [comment]
Closes with this [PR](https://github.com/reichlab/covidHubUtils/pull/118)
