### ISSUE TITLE
score_forecasts function

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#5]
Here is proposed documentation:

#' Score forecasts
#'
#' @param forecast_data optional data frame with forecasts in the format returned by `load_forecasts`
#' @param truth_data optional data frame with forecasts in the format returned by `load_truth`
#' @param scores character vector of scores to calculate: any of "wis", "wis_components", "error", "abs_error",
#' "squared_error", "interval_coverage", "quantile_coverage"
#' @param return_format string: "long" returns long format with a column for "score_name"
#' and a column for "score_value"; "wide" returns wide format with a separate column for each score.
#' 
#' @return data frame with columns model, forecast_date, location, inc_cum, death_case, 
#' horizon, target_end_date
#' If return_format is "long", also contains columns score_name and score_value where
#' score_name is one of wis, wis_width, wis_penalty_low, wis_penalty_high,
#' interval_coverage_<level> where level is 0.95 for a 95% confidence interval, or
#' quantile_coverage_<level> where level is 0.975 for a quantile level 0.975
#' score_value has the numeric value of the score.
#' If return_format is "wide", each calculated score is in its own column.
#' 
#' @export

This function would essentially call the `scoringutils::eval_forecasts` function and do some minor reorganization of the outputs.

**Comment by elray1** [comment]
Is the user required to first call `load_forecasts` and `load_truth` separately, or do we want a "convenience function" that additionally has all the parameters of `load_forecasts` and `load_truth` and calls those functions?  Such a convenience function would have a lot of arguments.

**Comment by elray1** [comment]
The proposal here is "tidy" but inefficient, in that there is a column for score_name and for score_value, and as a result many rows for the same combination of model, forecast_date, location, inc_cum, death_case, horizon, and target_end_date. Another alternative would have a separate column for each score, equivalent to taking the result as documented here and calling `pivot_wider(names_from = "score_name", values_from = "score_value")`.  If we do this instead of the proposal above, each row corresponds to a single forecast with scores for that forecast in columns.

**Comment by nickreich** [comment]
These specs look good to me. My thoughts:
 - we keep this as is, and later we could write a convenience function later if needed
 - we could add an argument that could return either wide or long format, depending on use, I could envision wanting the data in both formats.
 - we should add an "error" score, so that we could calculate, e.g. "average bias".

**Comment by elray1** [comment]
I updated the description in the issue above with the second two bullet points in nick's comment

**Comment by nickreich** [comment]
suggest we close this, as I've copied the relevant documentation in #10
