### ISSUE TITLE
create a truth-Incident Hospitalizations.csv file

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#50]
Do we want a truth-Incident Hospitalizations.csv file as part of the repo to go along with the similar files for incident and cumulative deaths and cases?  If so, the function to create it would belong in this package.

**Comment by ydhuang28** [comment]
I think as part of adding incident hospitalizations as a target that file will be created from our scripts.

**Comment by nickreich** [comment]
it won't be created automatically just because we add it as a target. I think we only really need to create the above file when/if we want to have a visualization? Otherwise, is it necessary?

**Comment by mzorn-58** [comment]
If we don't need it, can we close this issue @nick @evan?

**Comment by elray1** [comment]
yes, closing now

**Comment by elray1** [comment]
I am re-opening this issue since the file would be used to obtain truth data for plotting hospitalizations.
