### ISSUE TITLE
add location names/abbreviations to load_forecasts

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#52]
I think it would be super useful to have human-readable names of locations in the returned data from load_forecasts(). Is it complicated to add this as a final join before returning the data? @elray1 any reason not to do this?

**Comment by elray1** [comment]
I don't know of a reason not to do this.  maybe we should also do this in `load_truth`

**Comment by nickreich** [comment]
I'm going to work on this a bit. I have unassigned Serena for now.
