### ISSUE TITLE
change plot_forecast() to plot_forecasts()

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#68]
For consistency (e.g. with `score_forecasts()` and `scoringutils::eval_forecasts()`)  and better semantics, we should rename `plot_forecast()` to `plot_forecasts()`. For now, i think we should allow for back-compatibility and have plot_forecast() still function as an alias, but also throw a warning that it will be deprecated in future versions.

**Comment by elray1** [comment]
here's a SO post describing how to deal with this kind of situation gracefully

https://stackoverflow.com/questions/10099128/are-there-best-recommended-practices-to-follow-when-renaming-functions-in-a-new
