### ISSUE TITLE
add "sharpness"/"overprediction"/"underprediction" columns in score_forecast output

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#87]
Desired behavior is to return "sharpness"/"overprediction"/"underprediction" as new columns in the existing output for score_forecasts. These should be sums across the range-specific values for each forecast/observation.

**Comment by nikosbosse** [comment]
I think the only think that Yuxin needs to do is to add "sharpness", "overprediciton" and "underprediction" to the desired scores.

**Comment by nikosbosse** [comment]
(as in: he currently filters out everything not conforming to a list of scores and just needs to add these to the list)

**Comment by nickreich** [comment]
Yeah, I think there are some subtleties in the summing across all available scores for a particular grouped set of scores, but agree.
