### ISSUE TITLE
score_forecasts should throw a helpful error if quantile forecasts are not provided

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#89]
Currently, I think most/all scores rely on having quantile forecasts be present. e.g. the following fails with a not terribly useful error message because only point forecasts were extracted:
```
forecasts <- load_latest_forecasts(models=c("COVIDhub-ensemble", "UMass-MechBayes"), 
  last_forecast_date = "2020-12-14", 
  forecast_date_window_size = 7, 
  locations = c("US"), 
  targets = paste(1:4, "wk ahead inc death"), 
  types = "point",
  #source = "zoltar")
  source = "local_hub_repo",
  hub_repo_path = "../covid19-forecast-hub/")


truth <- load_truth("JHU", target_variable = "inc death", locations = "US")
scores <- score_forecasts(forecasts, truth)
```

error:
```
 Error in do.call(scoringutils::interval_score, c(list(true_value, lower,  : 
  object 'lower' not found 
```

**Comment by nickreich** [comment]
It seems like desired behavior would be to have only absolute error returned in this case. However the error seems to be happening on the scoringutils side of things, and the AE measure we are using right now is the AEM metric (absolute error of the median). Is there a simpler way to just call a "point prediction" version of the scoring function? As is, the score_forecasts() function seems more like a score_quantile_forecasts function.

**Comment by nickreich** [comment]
@nikosbosse is there functionality in scoringutils to handle this point forecast situation?

**Comment by nikosbosse** [comment]
I think I would need to put in a bit more thought to solve the general case (i.e. `eval_forecast` would need to recognize somehow that this is a point forecast only). 
For this specific use case in `score_forecasts()` I think the solution would be to simply return NA for that score if it can't be computed instead of throwing an error. Then the AEM would still be computed. I'll have a go at an implementation as soon as I can

**Comment by nikosbosse** [comment]
I created a two-part fix for this: 
on the scoringutils side, there is now a new PR: https://github.com/epiforecasts/scoringutils/pull/92
on the covidHubUtils side I also made a PR to address the case where aem_0 is not a column: https://github.com/reichlab/covidHubUtils/pull/92. I ran your example succesfully, but did not do further testing. Could you please review these two and check they are working? I'll merge it in scoringutils then. 
Also I changed it such that the interval_score is still computed for a point forecast assuming that is consistent with what we want. If we would prefer the interval score to show NA instead I can change that as well.

**Comment by nikosbosse** [comment]
oh these PRs really are twins and both have the number 92! small delights...

**Comment by nickreich** [comment]
Revisiting this issue. I ran the above code and it ran without error.
