### ISSUE TITLE
standardize representation of target variable

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#9]
I think we currently have 3 representations of the target variable; let's decide how we want to handle this.  All of this assumes that we will track the forecast horizon separately from the target variable.

 - the target field in the submission csvs concatenate the horizon with a string representation of the target variable as one of "wk ahead inc case", "wk ahead inc death", or "wk ahead cum death"
 - some functions use target_variable which is like "Incident Cases"
 - some functions use a combination of two categorical variables, `inc_cum` and `case_death`

I think I might prefer us to standardize around `target_variable` which is one of "inc case", "inc death", or "cum death"?

**Comment by nickreich** [comment]
I'm on board with standardizing around "inc case" "inc death", "cum death"

**Comment by nickreich** [comment]
if we choose to do this, should we create other specific issues to track needed changes?

**Comment by elray1** [comment]
Serena points out that we also have targets for hospitalizations, and there is a `temporal_resolution` concept like days or weeks to keep track of.  So what if we do:

**Comment by nickreich** [comment]
sounds good to me.
